FROM node:alpine
# workdir where everything in a container created will be stored
WORKDIR '/app' 

COPY package.json .
RUN npm install

# copy everything (public/, src/, etc into /app inside of the container)
COPY . . 
CMD ["npm", "run", "start"]